version: '2'

services:

    main:
        image: puffinrocks/ttrss:latest
        depends_on:
            - db
        ports:
            - 80
        environment:
            - VIRTUAL_HOST
            - VIRTUAL_PORT=80
            - DB_HOST=db
            - DB_PORT=5432
            - LETSENCRYPT_HOST
            - LETSENCRYPT_EMAIL
            - LETSENCRYPT_TEST
        networks:
            - front
            - back
            - default
        tmpfs:
            - /run
            - /tmp
    
    db:
        image: postgres
        environment:
            - POSTGRES_DB=ttrss
            - POSTGRES_USER=ttrss
            - POSTGRES_PASSWORD=ttrss
        volumes: 
            - db_data:/var/lib/postgresql/data

volumes:
    db_data:

networks:
    front:
        external:
            name: "puffin_front"
    back:
        external:
            name: "puffin_back"

